source 'https://rubygems.org'

gem 'rails', '4.0.3'
gem 'pg'
gem 'dotenv-rails'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'jbuilder', '~> 1.2'
gem 'jquery-rails'
gem 'coffee-rails', '~> 4.0.0'
gem 'turbolinks'
gem 'devise'
gem 'chronic'
gem 'time_difference'
gem 'foreman', require: false
gem 'pony'
gem 'sendgrid'

gem 'redis'
gem 'resque', '~> 2.0.0.pre.1', github: 'resque/resque'
