development:
  adapter: postgresql
  encoding: unicode
  database: ResqueLab_development
  pool: 5
  host: 'localhost'

test:
  adapter: postgresql
  encoding: unicode
  database: ResqueLab_test
  pool: 5
  host: 'localhost'
